export const ATTENTION_CONFIG = {
  TAB_BLUR_PENALTY: 15,
  TAB_FOCUS_RECOVERY: 5,
  ACTIVITY_RECOVERY: 2,
  INACTIVITY_THRESHOLD_MS: 30_000,
  INACTIVITY_PENALTY_PER_TICK: 5,
  INACTIVITY_MAX_PENALTY: 20,

  NO_FACE_PENALTY: 8,
  LOOKING_AWAY_PENALTY: 6,
  HEAD_TURNED_PENALTY: 5,
  FACE_RETURN_RECOVERY: 3,

  PROMPT_UNANSWERED_PENALTY: 10,
  REPEATED_CONFUSION_PENALTY: 8,

  HIGH_THRESHOLD: 75,
  MEDIUM_THRESHOLD: 50,
  LOW_THRESHOLD: 25,

  HIGH_DISTRACTION_COUNT: 3,

  WEBCAM_CHECK_INTERVAL_MS: 1_500,
  INACTIVITY_CHECK_INTERVAL_MS: 10_000,
  INTERVENTION_CHECK_INTERVAL_MS: 15_000,

  FACE_ABSENT_GRACE_MS: 3_000,
  LOOKING_AWAY_GRACE_MS: 4_000,
} as const;

export type AttentionEvent =
  | "PAGE_HIDDEN"
  | "PAGE_VISIBLE"
  | "WINDOW_BLUR"
  | "WINDOW_FOCUS"
  | "USER_IDLE"
  | "USER_ACTIVE"
  | "PROMPT_UNANSWERED"
  | "REPEATED_CONFUSION"
  | "FACE_PRESENT"
  | "NO_FACE"
  | "LOOKING_AWAY"
  | "HEAD_TURNED"
  | "POSSIBLE_CONFUSION";
