import json
import logging
import os
import ssl
from pathlib import Path

import aiohttp
import certifi
from dotenv import load_dotenv
from livekit.agents import Agent, AgentSession, JobContext, WorkerOptions, WorkerType, cli
from livekit.plugins import elevenlabs, openai, silero, simli

ROOT_DIR = Path(__file__).resolve().parents[1]
load_dotenv(ROOT_DIR / ".env.local", override=True)
load_dotenv(ROOT_DIR / ".env", override=False)

# macOS CA bundle fix for outbound TLS to OpenAI/Simli/ElevenLabs.
CA_BUNDLE = certifi.where()
os.environ.setdefault("SSL_CERT_FILE", CA_BUNDLE)
os.environ.setdefault("REQUESTS_CA_BUNDLE", CA_BUNDLE)
SSL_CONTEXT = ssl.create_default_context(cafile=CA_BUNDLE)

_original_create_default_context = ssl.create_default_context
_original_tcp_connector_init = aiohttp.TCPConnector.__init__


def _create_default_context_with_certifi(*args, **kwargs):
    if not args and "cafile" not in kwargs and "capath" not in kwargs and "cadata" not in kwargs:
        kwargs["cafile"] = CA_BUNDLE
    return _original_create_default_context(*args, **kwargs)


def _tcp_connector_init_with_certifi(self, *args, **kwargs):
    kwargs.setdefault("ssl", SSL_CONTEXT)
    return _original_tcp_connector_init(self, *args, **kwargs)


ssl.create_default_context = _create_default_context_with_certifi
ssl._create_default_https_context = _create_default_context_with_certifi
aiohttp.TCPConnector.__init__ = _tcp_connector_init_with_certifi

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("vertex.simli_agent")


def _tutor_name() -> str:
    """Return the tutor avatar name from the environment, never hardcoded."""
    return os.getenv("NEXT_PUBLIC_TUTOR_AVATAR_NAME", "Tutor").strip() or "Tutor"


def _required_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def _elevenlabs_api_key() -> str:
    return (
        os.getenv("ELEVENLABS_API_KEY", "").strip()
        or os.getenv("ELEVEN_API_KEY", "").strip()
    )


def _build_instructions(metadata: dict[str, object]) -> str:
    """Build the system instructions from dispatched metadata, with full tutoring context."""
    tutor_name = _tutor_name()
    child_name = str(metadata.get("childName") or "friend").strip() or "friend"

    # Use the rich instructions generated by the Next.js backend if available
    backend_instructions = str(metadata.get("instructions") or "").strip()

    chat_awareness = (
        "\n\nIMPORTANT CONTEXT ABOUT THE UI:\n"
        "- There is a companion CHAT PANEL beside your video where graphs and visuals appear.\n"
        "- When a graph or visual is generated, it shows up in the chat panel automatically.\n"
        "- When you see or discuss a graph, say something like 'check the graph in the chat panel' or "
        "'look at the graph I put in chat' so the student knows where to look.\n"
        "- Your spoken words appear as subtitles under your video, so keep responses conversational and concise.\n"
        "- Do NOT read out graph coordinates or equations verbally — just describe the key insight and tell them to look at the chat."
    )

    lang_rule = "\n\nIMPORTANT: Always respond in English only, regardless of what language the student speaks."

    if backend_instructions:
        return backend_instructions + chat_awareness + lang_rule

    # Fallback: minimal instructions if no context was dispatched
    return (
        f"You are {tutor_name}, a warm and encouraging live math tutor helping {child_name}. "
        "Only discuss math. If the child asks about unrelated topics, gently bring the conversation back to math help."
        + chat_awareness + lang_rule
    )


def _build_greeting(metadata: dict[str, object]) -> str:
    """Build the greeting instruction for generate_reply."""
    tutor_name = _tutor_name()
    child_name = str(metadata.get("childName") or "friend").strip() or "friend"
    return (
        f"Greet {child_name} warmly. Introduce yourself as {tutor_name}, "
        "say you're happy to work on math together today, "
        "and ask what math problem they'd like to start with."
    )


def _build_tts() -> elevenlabs.TTS:
    """Build ElevenLabs TTS with voice settings from env vars."""
    voice_id = _required_env("ELEVENLABS_VOICE_ID")
    api_key = _elevenlabs_api_key()
    if not api_key:
        raise RuntimeError("Missing ELEVENLABS_API_KEY or ELEVEN_API_KEY")

    return elevenlabs.TTS(
        voice_id=voice_id,
        api_key=api_key,
        model=os.getenv("ELEVENLABS_MODEL", "eleven_turbo_v2"),
        streaming_latency=2,
        voice_settings=elevenlabs.VoiceSettings(
            stability=float(os.getenv("ELEVENLABS_STABILITY", "0.7")),
            similarity_boost=float(os.getenv("ELEVENLABS_SIMILARITY_BOOST", "0.75")),
            style=float(os.getenv("ELEVENLABS_STYLE", "0.0")),
            use_speaker_boost=os.getenv("ELEVENLABS_SPEAKER_BOOST", "false").lower() != "false",
        ),
    )


async def entrypoint(ctx: JobContext):
    tutor_name = _tutor_name()
    metadata = json.loads(ctx.job.metadata or "{}")
    logger.info("Starting live tutor session", extra={"metadata": metadata, "tutor": tutor_name})

    # --- Chained pipeline: OpenAI STT → OpenAI LLM → ElevenLabs TTS ---
    session = AgentSession(
        stt=openai.STT(
            model=os.getenv("OPENAI_STT_MODEL", "gpt-4o-transcribe"),
            api_key=_required_env("OPENAI_API_KEY"),
        ),
        llm=openai.LLM(
            model=os.getenv("OPENAI_LLM_MODEL", "gpt-4o"),
            api_key=_required_env("OPENAI_API_KEY"),
        ),
        tts=_build_tts(),
        vad=silero.VAD.load(),
    )

    # --- Simli avatar ---
    simli_avatar = simli.AvatarSession(
        simli_config=simli.SimliConfig(
            api_key=_required_env("SIMLI_API_KEY"),
            face_id=os.getenv("SIMLI_FACE_ID", "cace3ef7-a4c4-425d-a8cf-a5358eb0c427"),
        ),
    )

    # Start the avatar first — it joins the room and waits for audio
    await simli_avatar.start(session, room=ctx.room)

    # Start the agent — it joins the room and begins listening
    await session.start(
        agent=Agent(instructions=_build_instructions(metadata)),
        room=ctx.room,
    )

    # Trigger the initial greeting
    await session.generate_reply(
        instructions=_build_greeting(metadata),
    )


if __name__ == "__main__":
    cli.run_app(
        WorkerOptions(
            entrypoint_fnc=entrypoint,
            worker_type=WorkerType.ROOM,
            agent_name=os.getenv("LIVEKIT_AGENT_NAME", "vertex-tutor"),
        )
    )
